name: Mark stale issues and pull requests

on:
  schedule:
    # Runs every day at 6:00 AM IST
    - cron: '30 0 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest

    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@v5
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue appears to be unresolved and has had no activity for a while. It will be closed automatically in 10 days if there is no further update.'
        stale-pr-message: 'This pull request appears to be unresolved and has had no activity for a while. It will be closed automatically in 10 days if there is no further update.'
        stale-issue-label: 'no-issue-activity'
        stale-pr-label: 'no-pr-activity'
        days-before-stale: 5
        days-before-close: 10
